"""
Numpy imports for interactive work or simulation code.
"""

import numpy as np
from numpy.ma import MaskedArray
from numpy.random import (
        permutation,
        rand,
        randint,
        random_sample,
        randn,
        sample,
        seed,
)
from numpy import (
        absolute,
        abs as abs_,
        all as all_,
        any as any_,
        atleast_1d,
        atleast_2d,
        arange,
        arccos,
        arcsin,
        arctan2,
        argmax,
        argmin,
        argsort,
        array,
        average,
        block,
        broadcast_arrays,
        broadcast_to,
        c_,
        ceil,
        clip,
        column_stack,
        concatenate,
        cos,
        diag,
        diff,
        dot,
        dsplit,
        dstack,
        empty,
        empty_like,
        exp,
        expm1,
        eye,
        floor,
        histogram,
        hsplit,
        hstack,
        hypot,
        inf,
        invert,
        isclose,
        isfinite,
        isnan,
        isscalar,
        lexsort,
        linspace,
        log,
        log1p,
        log2,
        log10,
        ma,
        matmul,
        max as max_,
        mean,
        median,
        meshgrid,
        min as min_,
        nan,
        ndarray,
        ndim,
        newaxis as AX,
        newaxis,
        nextafter,
        ones,
        ones_like,
        pi,
        power,
        r_,
        random,
        repeat,
        sin,
        sign,
        size,
        sqrt,
        std,
        sum as sum_,
        tan,
        tanh,
        tensordot,
        trapz,
        unique,
        vsplit,
        vstack,
        zeros,
        zeros_like,
)
