"""
Globstar numpy imports for interactive work or simulation code.
"""

import numpy as np
from numpy.ma import MaskedArray
from numpy.random import (
        permutation,
        rand,
        randint,
        random_sample,
        randn,
        sample,
        seed,
)
from numpy import (
        absolute,
        any,
        atleast_1d,
        atleast_2d,
        arange,
        arccos,
        arcsin,
        arctan2,
        array,
        average,
        broadcast_arrays,
        broadcast_to,
        c_,
        clip,
        cos,
        diag,
        dot,
        empty,
        empty_like,
        exp,
        expm1,
        eye,
        histogram,
        hstack,
        hypot,
        inf,
        isclose,
        isfinite,
        linspace,
        log,
        log1p,
        ma,
        matmul,
        meshgrid,
        nan,
        ndarray,
        newaxis as AX,
        newaxis,
        nextafter,
        ones,
        ones_like,
        pi,
        power,
        r_,
        random,
        repeat,
        sin,
        size,
        sqrt,
        tan,
        tanh,
        tensordot,
        unique,
        vstack,
        zeros,
        zeros_like,
)
