#!/usr/bin/env bash
set -e

# Toolbox runfile

USAGE="Usage: run -e|(m)vim|(un)install|exportenv|ipython|cluster|notebook"

if (( $# )); then
    runcmd="$1"
    shift
else
    echo "$USAGE"
    exit 1
fi


# Add run commands as switch cases below. Do not make edits
# outside of case blocks. Note: Optional args are available
# as "${@}". If used, consider the first line in the block
# as a usage statement.


SESSFILE="$HOME/projects/toolbox/session.vim"
NBDIR="$HOME/projects/toolbox/notebooks"

function __conda_check {
    if [[ "${CONDA_DEFAULT_ENV+x}" ]]; then
        if [[ "$CONDA_DEFAULT_ENV" != "/Users/joe/projects/toolbox/conda" ]]; then
            echo "Wrong environment ($CONDA_DEFAULT_ENV). Please activate "
            echo "'toolbox' with 'conda activate /Users/joe/projects/toolbox/conda'."
            exit 1
        fi
    else
        echo "Please run 'conda activate /Users/joe/projects/toolbox/conda' first."
        exit 2
    fi
}


case "$runcmd" in

vim)
    if [[ -r "$SESSFILE" ]]; then
        vim -S "$SESSFILE" 2>/dev/null
    else
        vim +"Obsession $SESSFILE" 2>/dev/null
    fi
    ;;

mvim)
    if [[ -r "$SESSFILE" ]]; then
        mvim -S "$SESSFILE" 2>/dev/null
    else
        mvim +"Obsession $SESSFILE" 2>/dev/null
    fi
    ;;

install)
    pip install --no-deps -e "/Users/joe/code/tools" ;;

uninstall)
    pip uninstall -y toolbox
    ;;

ipython)
    __conda_check
    ipython --profile-dir="/Users/joe/projects/toolbox/ipython"
    ;;

cluster)
    __conda_check
    ipcluster start --profile-dir="/Users/joe/projects/toolbox/ipython"
    ;;

notebook)
    __conda_check
    [[ ! -d "$NBDIR" ]] && mkdir -p "$NBDIR"
    jupyter notebook --notebook-dir="$NBDIR" &
    ;;

killnb) pkill -f jupyter ;;

finder) open . -a finder ;;

tests) py.test -q tests ;;

*)
    echo $USAGE
    exit 1
    ;;

esac
